/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  opcatDocsSidebar: [
    'overview',
    'difference-from-bitcoin',
    'send-a-transaction',
    {
      type: 'category',
      label: 'How to Write a Contract',
      items: [{
        type: 'autogenerated',
        dirName: 'how-to-write-a-contract',
      }
      ],
    },
    {
      type: 'category',
      label: 'How to Deploy and Call a Contract',
      items: [{
        type: 'autogenerated',
        dirName: 'how-to-deploy-and-call-a-contract',
      }
      ],
    },
  ],
  };
  
  module.exports = sidebars;
  