/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  opcatDocsSidebar: [
    {
      type: "category",
      label: "Overview",
      items: ["overview", "overview/key-differences"],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        "core-concepts/utxo-model",
        "core-concepts/consensus-and-fee-model",
        "core-concepts/bridge-mechanism",
        {
          type: "category",
          label: "Token Standards",
          items: [
            "core-concepts/token-standards/overview",
            "core-concepts/token-standards/cat20",
            "core-concepts/token-standards/cat721",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Developer Guides",
      items: [
        "developer-guides/install-cli-and-sdk",
        "developer-guides/connect-to-testnet",
        "developer-guides/send-a-transaction",
        {
          type: "category",
          label: "Smart Contract Development",
          items: [
            {
              type: "autogenerated",
              dirName: "smart-contract-development/how-to-write-a-contract",
            },
            {
              type: "autogenerated",
              dirName:
                "smart-contract-development/how-to-deploy-and-call-a-contract",
            },
            "smart-contract-development/how-to-debug-a-contract",
          ],
        },
        {
          type: "category",
          label: "dApp Development",
          items: [
            {
              type: "doc",
              id: "dapp-development/frontend-integration",
              label: "Front-end Integration",
            },
            {
              type: "doc",
              id: "dapp-development/wallet-integration",
              label: "Wallet Integration",
            },
            {
              type: "category",
              label: "CAT Token Integration",
              items: [
                {
                  type: "autogenerated",
                  dirName: "dapp-development/cat-token-integration",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      items: [{ type: "autogenerated", dirName: "tutorials" }],
    },
    {
      type: "category",
      label: "API & SDK Reference",
      items: [
        {
          type: "category",
          label: "@opcat-labs/scrypt-ts-opcat",
          items: [{ type: "autogenerated", dirName: "references/opcat-labs_scrypt-ts-opcat" }],
        },
        {
          type: "category",
          label: "@opcat-labs/cat-sdk",
          items: [{ type: "autogenerated", dirName: "references/opcat-labs_cat-sdk" }],
        },
        "api/openapi",
        "api/opcat-wallet",
      ],
    },
  ],
};

module.exports = sidebars;
